// src/lit/ShikiMagicMovePrecompiled.ts
import type { KeyedTokensInfo, MagicMoveDifferOptions, MagicMoveRenderOptions } from '../types'
import { html, LitElement } from 'lit'
import { customElement, property } from 'lit/decorators.js'
import { syncTokenKeys, toKeyedTokens } from '../core'

import './ShikiMagicMoveRenderer'

@customElement('shiki-magic-move-precompiled')
export class ShikiMagicMovePrecompiled extends LitElement {
  @property()
  steps: KeyedTokensInfo[] = []

  @property()
  step: number = 0

  @property()
  animated: boolean = true

  @property()
  options?: MagicMoveRenderOptions & MagicMoveDifferOptions

  previous: KeyedTokensInfo = toKeyedTokens('', [])

  createRenderRoot() {
    // Disable shadow DOM.
    return this
  }

  render() {
    const result = syncTokenKeys(
      this.previous,
      this.steps[Math.min(this.step, this.steps.length - 1)],
      this.options,
    )
    this.previous = result.to

    return html`<shiki-magic-move-renderer
      .tokens=${result.to}
      .previous=${result.from}
      .options=${this.options}
      .animate=${this.animated}
      @onStart=${() => this.dispatchEvent(new CustomEvent('onStart'))}
      @onEnd=${() => this.dispatchEvent(new CustomEvent('onEnd'))}
    ></shiki-magic-move-renderer>`
  }
}

// src/svelte/ShikiMagicMovePrecompiled.svelte
<script lang='ts'>
  import { syncTokenKeys, toKeyedTokens } from 'shiki-magic-move/core'
  import type { KeyedTokensInfo, MagicMoveDifferOptions, MagicMoveRenderOptions } from 'shiki-magic-move/types'
  import ShikiMagicMoveRenderer from './ShikiMagicMoveRenderer.svelte'

  interface ShikiMagicMovePrecompileProps {
    steps: KeyedTokensInfo[]
    step?: number
    animate?: boolean
    options?: MagicMoveRenderOptions & MagicMoveDifferOptions
    onStart?: () => void
    onEnd?: () => void
  }

  const {
    steps,
    step = 0,
    animate = true,
    options,
    onStart,
    onEnd,
  }: ShikiMagicMovePrecompileProps = $props()

  const EMPTY = toKeyedTokens('', [])

  let previous = EMPTY
  const result = $derived.by(() => {
    if (steps.length === 0)
      return
    const res = syncTokenKeys(previous, steps[Math.min(step, steps.length - 1)], options)
    previous = res.to
    return res
  })
</script>

{#if result}
  <ShikiMagicMoveRenderer
    tokens={result.to}
    previous={result.from}
    {options}
    {animate}
    {onStart}
    {onEnd}
  />
{/if}
