// src/svelte/ShikiMagicMoveRenderer.svelte
<script lang="ts">
	import { MagicMoveRenderer } from '../renderer'
	import type { MagicMoveRenderOptions, KeyedTokensInfo } from '../types.d.ts'

	interface ShikiMagicMoveRendererProps {
		class?: string
		animate?: boolean
		tokens: KeyedTokensInfo
		previous?: KeyedTokensInfo
		options?: MagicMoveRenderOptions
		onStart?: () => void
		onEnd?: () => void
	}

	const {
		animate = true,
		tokens,
		previous,
		options,
		onStart,
		onEnd,
		...props
	}: ShikiMagicMoveRendererProps = $props()

	let container: HTMLPreElement
	let renderer: MagicMoveRenderer
	let isMounted = $state(false)
	
	$effect(() => {
		if (!container) return
		container.innerHTML = ''
		isMounted = true
		renderer = new MagicMoveRenderer(container)
	})

	$effect(() => {
		async function render() {
			if (!renderer) return
			Object.assign(renderer.options, options)
			if (animate) {
				if (previous) renderer.replace(previous)
				onStart?.()
				await renderer.render(tokens)
				onEnd?.()
			} else {
				renderer.replace(tokens)
			}
		}
		render()
	})
</script>

<pre bind:this={container} class="shiki-magic-move-container {props?.class}" {...props}>
  <!-- render initial tokens for SSR -->
  {#if !isMounted}
		{#each tokens.tokens as token (token.key)}
			{#if token.content === '\n'}
				<br />
			{/if}
      <span
				class="shiki-magic-move-item"
				style:color={token.color}
				style={token.htmlStyle}>
        {token.content}
      </span>
		{/each}
	{/if}
</pre>

// src/lit/ShikiMagicMoveRenderer.ts
import type { Ref } from 'lit/directives/ref.js'
import type { KeyedTokensInfo, MagicMoveRenderOptions } from '../types'
import { html, LitElement } from 'lit'
import { customElement, property } from 'lit/decorators.js'
import { createRef, ref } from 'lit/directives/ref.js'
import { MagicMoveRenderer as Renderer } from '../renderer'

@customElement('shiki-magic-move-renderer')
export class ShikiMagicMoveRenderer extends LitElement {
  @property()
  animated: boolean = true

  @property()
  tokens?: KeyedTokensInfo

  @property()
  previous?: KeyedTokensInfo

  @property()
  options?: MagicMoveRenderOptions

  @property()
  class: string = ''

  container: Ref<HTMLPreElement> = createRef()

  renderer?: Renderer

  createRenderRoot() {
    // Disable shadow DOM.
    return this
  }

  async transform() {
    if (this.renderer) {
      if (this.animated) {
        if (this.previous)
          this.renderer.replace(this.previous)
        this.dispatchEvent(new CustomEvent('onStart'))
        if (this.tokens)
          await this.renderer?.render(this.tokens)
        this.dispatchEvent(new CustomEvent('onEnd'))
      }
      else if (this.tokens) {
        this.renderer.replace(this.tokens)
      }
    }
  }

  shouldUpdate(changedProperties: Map<string, any>) {
    if (this.hasUpdated) {
      if (this.renderer) {
        if (changedProperties.has('options'))
          Object.assign(this.renderer?.options, changedProperties.get('options'))
        this.transform()
        return false
      }
    }
    return true
  }

  firstUpdated() {
    this.renderer = new Renderer(this.container.value!)
    if (this.tokens)
      this.renderer?.render(this.tokens)
  }

  render() {
    return html`<pre ${ref(this.container)} class="shiki-magic-move-container ${this.class}"></pre>`
  }
}
