// src/svelte/ShikiMagicMove.svelte
<script lang="ts">
	import { codeToKeyedTokens, createMagicMoveMachine } from '../core'
	import ShikiMagicMoveRenderer from './ShikiMagicMoveRenderer.svelte'
	import type { HighlighterCore } from 'shiki/core'
	import type { MagicMoveRenderOptions, MagicMoveDifferOptions } from '../types'
	
	interface ShikiMagicMoveProps {
		highlighter: HighlighterCore
		lang: string
		theme: string
		code: string
		options?: MagicMoveRenderOptions & MagicMoveDifferOptions
		onStart?: () => void
		onEnd?: () => void
	}

	const { highlighter, lang, theme, code, options, onStart, onEnd, ...props }: ShikiMagicMoveProps = $props()
	const machine = createMagicMoveMachine(
		(code) => codeToKeyedTokens(highlighter, code, { lang, theme }),
		options
	)
	const result = $derived(machine.commit(code))
</script>

<ShikiMagicMoveRenderer
	tokens={result.current}
	previous={result.previous}
	{options}
	{onStart}
	{onEnd}
	{...props}
/>

// src/react/ShikiMagicMove.tsx
import * as React from 'react'
import type { HighlighterCore } from 'shiki/core'
import { codeToKeyedTokens, createMagicMoveMachine } from '../core'
import type { KeyedTokensInfo, MagicMoveDifferOptions, MagicMoveRenderOptions } from '../types'
import { ShikiMagicMoveRenderer } from './ShikiMagicMoveRenderer'

export interface ShikiMagicMoveProps {
  highlighter: HighlighterCore
  lang: string
  theme: string
  code: string
  options?: MagicMoveRenderOptions & MagicMoveDifferOptions
  onStart?: () => void
  onEnd?: () => void
  className?: string
}

export function ShikiMagicMove(props: ShikiMagicMoveProps) {
  const codeToTokens = React.useRef<(code: string) => KeyedTokensInfo>()
  codeToTokens.current = code => codeToKeyedTokens(props.highlighter, code, {
    lang: props.lang,
    theme: props.theme,
  })

  const machine = React.useRef<ReturnType<typeof createMagicMoveMachine>>()
  machine.current = machine.current || createMagicMoveMachine(
    code => codeToTokens.current!(code),
  )

  const result = React.useMemo(
    () => machine.current!.commit(props.code, props.options),
    [props.code, props.options],
  )

  return (
    <ShikiMagicMoveRenderer
      tokens={result.current}
      options={props.options}
      previous={result.previous}
      onStart={props.onStart}
      onEnd={props.onEnd}
      className={props.className}
    />
  )
}
